config/routes.rb
Rails.application.routes.draw do
  get 'messages/send'
  root to: "home#index"
  devise_for :users
  resources :lists do
    resources :contacts, only: [:create, :update, :edit, :destroy]
    resources :messages, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :list
  has_many :messages
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :contacts

  def create_messages(message_params)
    transaction do
      contacts.each do |contact|
        # this seems to not be working. Repeat message con be sent!
        message = contact.messages.find_or_create_by!(content: message_params[:content])
        message.send_sms!
        message.update(sent_at: Time.now)
      end
    rescue
      return false
    end
    true
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :contact
  validates :content, presence: true

  def send_sms!
    return if sent?
    # TODO: throw an exception if Twilio can't send the sms
    TwilioService.send_sms(to: contact.phone_number, content: content)
  end

  private

  def sent?
    !!sent_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_list
  before_action :set_contact, except: :create

  def create
    @contact = @list.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @list, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { redirect_to @list }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def edit
  end

  def destroy
    @contact.destroy
    redirect_to list_path(@list)
  end

  private

  def set_contact
    @contact = @list.contacts.find(params[:id])
  end

  def set_list
    @list = current_user.lists.find(params[:list_id])
  end

  def contact_params
    params.require(:contact).permit(:name, :phone_number, :list_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @contact = Contact.new
  end

  # GET /lists/new
  def new
    @list = current_user.lists.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :user_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @list = current_user.lists.find(params[:list_id])
    @message = Message.new
  end

  def create
    @list = current_user.lists.find(params[:list_id])

    if @list.create_messages(message_params)
      redirect_to @list, notice: "Message sent to list!"
    else
      redirect_to @list, notice: "There was a problem."
    end
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/edit.html.erb
<h1>Contacts#edit</h1>
<p>Find me in app/views/contacts/edit.html.erb</p>

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsThem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } %>
    <% end %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th># contacts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.contacts.count %></td>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<p>
  <% if @list.contacts.any? %>
    <strong>Contacts:</strong>
    <% @list.contacts.each do |contact| %>
      <%= contact.name %> | <%= contact.phone_number %> >> <%= link_to 'Edit', edit_list_contact_path(@list, contact) %> | <%= link_to 'Destroy', [@list, contact], method: :delete, data: { confirm: 'Are you sure?' } %>
      <br>
    <% end %>
  <% else %>
    <strong>No contacts in this list yet...</strong>
  <% end %>
</p>

<br>
<hr>
<br>

<%= link_to "Send message to list!", new_list_message_path(@list) %>

<br>
<hr>
<br>

<%= form_with(model: [@list, @contact], local: true) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Edit list name', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

<%= form_with(model: [@list, @message], local: true) do |form| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% @message.errors.full_messages.each do |error_message| %>
          <li><%= error_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 15, cols: 60 %>
  </div>

  <div class="actions">
    <%= form.submit "Send message", data: { confirm: "This will send the above message to #{pluralize(@list.contacts.count, "contact")} in #{@list.name}. Are you sure you want to continue?" } %>
  </div>
<% end %>